import Skateboarder from "/src/assets/stockPhotos/skateboarder.jpg";
import CatDog from "/src/assets/stockPhotos/catdog.jpg";
import Dog from "/src/assets/stockPhotos/dog.jpg";
import WomanSitting from "/src/assets/stockPhotos/woman_sitting.jpg";
import Squirrel from "/src/assets/stockPhotos/squirrel.jpg";

const photoData = [
  Dog,
  WomanSitting,
  Squirrel,
  Skateboarder,
  CatDog,
  Dog,
  WomanSitting,
  Squirrel,
  Skateboarder,
  CatDog,
  Dog,
  WomanSitting,
  Squirrel,
  Skateboarder,
  CatDog,
  Dog,
  WomanSitting,
  Squirrel,
  Skateboarder,
  CatDog,
  Dog,
  WomanSitting,
  Squirrel,
  Skateboarder,
  CatDog,
  Dog,
  WomanSitting,
  Squirrel,
  Skateboarder,
  CatDog,
  Dog,
  WomanSitting,
  Squirrel,
  Skateboarder,
  CatDog,
  Dog,
  WomanSitting,
  Squirrel,
  Skateboarder,
  CatDog,
  Dog,
  WomanSitting,
  Squirrel,
  Skateboarder,
  CatDog,
  Dog,
  WomanSitting,
  Squirrel,
  Skateboarder,
  CatDog,
  Dog,
  WomanSitting,
  Squirrel,
  Skateboarder,
  CatDog,
  Dog,
  WomanSitting,
  Squirrel,
  Skateboarder,
  CatDog,
  Dog,
  WomanSitting,
  Squirrel,
  Skateboarder,
  CatDog,
  Dog,
  WomanSitting,
  Squirrel,
  Skateboarder,
  CatDog,
  Dog,
  WomanSitting,
  Squirrel,
];

export default photoData;
