const photoData = [
  "/src/assets/stockPhotos/skateboarder.jpg",
  "/src/assets/stockPhotos/catdog.jpg",
  "/src/assets/stockPhotos/woman_sitting.jpg",
  "/src/assets/stockPhotos/catdog.jpg",
  "/src/assets/stockPhotos/woman_sitting.jpg",
  "/src/assets/stockPhotos/skateboarder.jpg",
  "/src/assets/stockPhotos/catdog.jpg",
  "/src/assets/stockPhotos/woman_sitting.jpg",
  "/src/assets/stockPhotos/skateboarder.jpg",
  "/src/assets/stockPhotos/catdog.jpg",
  "/src/assets/stockPhotos/skateboarder.jpg",
  "/src/assets/stockPhotos/woman_sitting.jpg",
  "/src/assets/stockPhotos/skateboarder.jpg",
  "/src/assets/stockPhotos/catdog.jpg",
  "/src/assets/stockPhotos/woman_sitting.jpg",
  "/src/assets/stockPhotos/skateboarder.jpg",
  "/src/assets/stockPhotos/catdog.jpg",
  "/src/assets/stockPhotos/woman_sitting.jpg",
  "/src/assets/stockPhotos/skateboarder.jpg",
  "/src/assets/stockPhotos/catdog.jpg",
  "/src/assets/stockPhotos/woman_sitting.jpg",
  "/src/assets/stockPhotos/skateboarder.jpg",
  "/src/assets/stockPhotos/catdog.jpg",
  "/src/assets/stockPhotos/woman_sitting.jpg",
  "/src/assets/stockPhotos/skateboarder.jpg",
  "/src/assets/stockPhotos/catdog.jpg",
  "/src/assets/stockPhotos/woman_sitting.jpg",
  "/src/assets/stockPhotos/skateboarder.jpg",
  "/src/assets/stockPhotos/catdog.jpg",
  "/src/assets/stockPhotos/woman_sitting.jpg",
];

export default photoData;
