const filterDataCustom = {
  filters: [
    {
      type: "slider",
      name: "Contrast",
      min: "0",
      value: "100",
      max: "200",
      unit: "%",
    },
    {
      type: "slider",
      name: "Brightness",
      min: "0",
      value: "100",
      max: "200",
      unit: "%",
    },
    {
      type: "slider",
      name: "Saturate",
      min: "0",
      value: "100",
      max: "200",
      unit: "%",
    },
    {
      type: "slider",
      name: "Sepia",
      min: "0",
      value: "100",
      max: "200",
      unit: "%",
    },
    {
      type: "slider",
      name: "Grayscale",
      min: "0",
      value: "100",
      max: "200",
      unit: "%",
    },
    {
      type: "slider",
      name: "Invert",
      min: "0",
      value: "100",
      max: "200",
      unit: "%",
    },
    {
      type: "slider",
      name: "Hue Rotate",
      min: "0",
      value: "0",
      max: "360",
      unit: "deg",
    },
    {
      type: "slider",
      name: "Blur",
      min: "0",
      value: "0",
      max: "10",
      unit: "px",
    },
  ],
  overlay: {
    type: "None",
    value: null,
  },
};

const filterDataPresets = [
  { filter: "1977", className: "_1977" },
  { filter: "Aden", className: "aden" },
  { filter: "Amaro", className: "amaro" },
  { filter: "Brannan", className: "brannan" },
  { filter: "Brooklyn", className: "brooklyn" },
  { filter: "Clarendon", className: "clarendon" },
  { filter: "Gingham", className: "gingham" },
  { filter: "Hudson", className: "hudson" },
  { filter: "Inkwell", className: "inkwell" },
  { filter: "Kelvin", className: "kelvin" },
  { filter: "Lark", className: "lark" },
  { filter: "Lo-fi", className: "lofi" },
  { filter: "Mayfair", className: "mayfair" },
  { filter: "Moon", className: "moon" },
  { filter: "Nashville", className: "nashville" },
  { filter: "Perpetua", className: "perpetua" },
  { filter: "Reyes", className: "reyes" },
  { filter: "Rise", className: "rise" },
  { filter: "Slumber", className: "slumber" },
  { filter: "Stinson", className: "stinson" },
  { filter: "Toaster", className: "toaster" },
  { filter: "Valencia", className: "valencia" },
  { filter: "Walden", className: "walden" },
  { filter: "Willow", className: "willow" },
  { filter: "X-Pro-2", className: "xpro2" },
];

export { filterDataCustom, filterDataPresets };
